apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: kees2-drift-baseline
    namespace: confluent
    files:
      - baseline.yaml=wo-05-configuration-baseline-example.yaml

resources:
  - wo-05-drift-cronjob.yaml
  - wo-13-prometheus-rules.yaml
  - wo-16-slo-prometheus-rules.yaml
  - wo-15-slo-synthetic-cronjob.yaml
  - wo-16-slo-report-cronjob.yaml
  - wo-13-alertmanager-configmap.yaml
